name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "0.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc47eb754d17e4b9b249d45c5ba5b4c801ced3e849f1caa3cc76340eea04bc13"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
