[[markers]]
	type = "target_x"
	z = 39
	x = 38
	name = "{\"text\":\"City Hall\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "target_x"
	z = 56
	x = -97
	name = "{\"text\":\"Grand Central\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "target_x"
	z = 414
	x = -449
	name = "{\"text\":\"Stage\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "target_x"
	z = -294
	x = -166
	name = "{\"text\":\"HQ\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 182
	x = 107
	name = "{\"text\":\"Arrábida\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 473
	x = -449
	name = "{\"text\":\"Nova Graciosa\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 279
	x = 158
	name = "{\"text\":\"Tróia Peninsula\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 204
	x = 272
	name = "{\"text\":\"Estuário do Sado\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 149
	x = 37
	name = "{\"text\":\"Azeitão\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = 115
	x = -172
	name = "{\"text\":\"Lagoa de Albufeira\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = -136
	x = -275
	name = "{\"text\":\"Farol do Bugio\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = -355
	x = -374
	name = "{\"text\":\"Sintra-Cascais\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = -168
	x = -181
	name = "{\"text\":\"Torre de Belém\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = -224
	x = -115
	name = "{\"text\":\"Monstanto\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "monument"
	z = -362
	x = 149
	name = "{\"text\":\"Estuário do Tejo\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "mansion"
	z = -400
	x = -70
	name = "{\"text\":\"Ferris Wheel\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "mansion"
	z = -445
	x = -189
	name = "{\"text\":\"Log Flume\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -236
	x = 437
	name = "{\"text\":\"Origins- & TMO\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_green"
	z = -301
	x = 194
	name = "{\"text\":\"Tinkerer's Smithing\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = -346
	x = -179
	name = "{\"text\":\"Switchy\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = 73
	x = 103
	name = "{\"text\":\"Pollinators' Paradise\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -167
	x = 154
	name = "{\"text\":\"Moue Milkshakes\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = -106
	x = 288
	name = "{\"text\":\"Automobility\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = 1
	x = 210
	name = "{\"text\":\"Bovines & Buttercups\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = 19
	x = 170
	name = "{\"text\":\"Missing Wilds\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = 115
	x = 140
	name = "{\"text\":\"Ochetgenyo\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = 67
	x = 146
	name = "{\"text\":\"Milk+\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = 25
	x = -44
	name = "{\"text\":\"Figura\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = 27
	x = -25
	name = "{\"text\":\"Packages\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 42
	x = -3
	name = "{\"text\":\"Templates 2\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = 78
	x = -4
	name = "{\"text\":\"TerrariaMod\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 63
	x = -44
	name = "{\"text\":\"Promenade\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_green"
	z = 0
	x = -66
	name = "{\"text\":\"Yardwork\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_gray"
	z = -39
	x = -81
	name = "{\"text\":\"SpindleMark\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -73
	x = -121
	name = "{\"text\":\"BounceCraft3\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -216
	x = -143
	name = "{\"text\":\"Discarnate\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = -250
	x = -129
	name = "{\"text\":\"Succ\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -256
	x = -170
	name = "{\"text\":\"PortalCubed\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = -262
	x = -198
	name = "{\"text\":\"Ext. Drawers\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = -270
	x = -216
	name = "{\"text\":\"Adv. Networking\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = -237
	x = -237
	name = "{\"text\":\"EMI\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -259
	x = -259
	name = "{\"text\":\"Exco\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = -277
	x = -260
	name = "{\"text\":\"Lucky Ducks\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -262
	x = -338
	name = "{\"text\":\"Calibrated Access\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -280
	x = -341
	name = "{\"text\":\"The Printer\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = -329
	x = -288
	name = "{\"text\":\"CC:C Bridge\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = -352
	x = -285
	name = "{\"text\":\"Arcpocalypse\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = -359
	x = -271
	name = "{\"text\":\"Honk\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_green"
	z = -343
	x = -266
	name = "{\"text\":\"CactusFix\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -337
	x = -197
	name = "{\"text\":\"Pehkui\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = -356
	x = -141
	name = "{\"text\":\"Mycoturgy\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = -338
	x = -116
	name = "{\"text\":\"Affectionate\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -331
	x = -87
	name = "{\"text\":\"Engination\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -356
	x = -110
	name = "{\"text\":\"Lovely Snails\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = -205
	x = -184
	name = "{\"text\":\"Endrich\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -80
	x = -149
	name = "{\"text\":\"Tropics\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = -24
	x = 27
	name = "{\"text\":\"Plushables\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = -26
	x = 68
	name = "{\"text\":\"Green Screen\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = 3
	x = 78
	name = "{\"text\":\"FEN\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_black"
	z = -13
	x = 100
	name = "{\"text\":\"Controllify\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = -41
	x = 133
	name = "{\"text\":\"Scriptor Magicae\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = -25
	x = 142
	name = "{\"text\":\"Softer Pastels\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -37
	x = 174
	name = "{\"text\":\"Map Zones\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = -59
	x = 180
	name = "{\"text\":\"FoxBox\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -45
	x = 226
	name = "{\"text\":\"Utility Belt\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = 57
	x = 207
	name = "{\"text\":\"Better Enchantment Boosting\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = 83
	x = 254
	name = "{\"text\":\"Scarves\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = 66
	x = 375
	name = "{\"text\":\"Wanderering Wizardry\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = 140
	x = -49
	name = "{\"text\":\"Styled Series\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 148
	x = -119
	name = "{\"text\":\"Brewery\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = 144
	x = -157
	name = "{\"text\":\"Polyfactory\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = -210
	x = 286
	name = "{\"text\":\"Table Saw\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -188
	x = 262
	name = "{\"text\":\"Arch Ex\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = 275
	x = 421
	name = "{\"text\":\"Elysium\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 285
	x = 438
	name = "{\"text\":\"Halfdoors\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = 303
	x = 445
	name = "{\"text\":\"Wanderer's Catalogue\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = -380
	x = -318
	name = "{\"text\":\"Hazard Diamond\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_magenta"
	z = -245
	x = -300
	name = "{\"text\":\"Hex Casting\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = 152
	x = -63
	name = "{\"text\":\"Image2Map\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_gray"
	z = 167
	x = -48
	name = "{\"text\":\"BanHammer\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = 169
	x = -74
	name = "{\"text\":\"Universal Graves\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = 153
	x = -99
	name = "{\"text\":\"ASE\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = 176
	x = -129
	name = "{\"text\":\"Nucleoid\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = 120
	x = -130
	name = "{\"text\":\"Polydex\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = 114
	x = -119
	name = "{\"text\":\"GOML\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = 119
	x = -92
	name = "{\"text\":\"Universal Shops\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = 99
	x = -51
	name = "{\"text\":\"PolyMC\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_magenta"
	z = -347
	x = -125
	name = "{\"text\":\"Aurora's Deco\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 40
	x = -96
	name = "{\"text\":\"Steam'n'Rails\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = -107
	x = -161
	name = "{\"text\":\"Rainglow\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = -280
	x = -306
	name = "{\"text\":\"HOTM\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = -244
	x = -221
	name = "{\"text\":\"WIAJ\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_black"
	z = -280
	x = -228
	name = "{\"text\":\"ShadowsGate\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = -280
	x = -193
	name = "{\"text\":\"Phonos\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_magenta"
	z = -303
	x = -23
	name = "{\"text\":\"Mythic Metals\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = -278
	x = -386
	name = "{\"text\":\"Consistency+\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_cyan"
	z = -290
	x = -403
	name = "{\"text\":\"Soul Ice\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -295
	x = -389
	name = "{\"text\":\"WYD\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -232
	x = -289
	name = "{\"text\":\"Hexal\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = -235
	x = -275
	name = "{\"text\":\"Hexbound\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_gray"
	z = -260
	x = -244
	name = "{\"text\":\"Yttr\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_gray"
	z = -304
	x = -284
	name = "{\"text\":\"UPW\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = -3
	x = 333
	name = "{\"text\":\"Turtlematic\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_pink"
	z = 316
	x = 444
	name = "{\"text\":\"Amarite\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = 335
	x = 442
	name = "{\"text\":\"DJA\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = 337
	x = 435
	name = "{\"text\":\"Piercing Paxels\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_green"
	z = 344
	x = 423
	name = "{\"text\":\"Befoul\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = 306
	x = 355
	name = "{\"text\":\"V. Barriers\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = 337
	x = 355
	name = "{\"text\":\"Peculiar Pieces\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = 331
	x = 368
	name = "{\"text\":\"Trails&Tweaks\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 333
	x = 354
	name = "{\"text\":\"DecoMod\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = 286
	x = 363
	name = "{\"text\":\"Icy Incitement\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_black"
	z = 122
	x = 323
	name = "{\"text\":\"Arachne\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_purple"
	z = 128
	x = 386
	name = "{\"text\":\"Enchantery\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_green"
	z = 110
	x = 408
	name = "{\"text\":\"PIAJ\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = 69
	x = 422
	name = "{\"text\":\"Bing Bing Wahoo\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_red"
	z = 10
	x = 411
	name = "{\"text\":\"Fedicraft\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_lime"
	z = -39
	x = 497
	name = "{\"text\":\"Ecotones\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = -23
	x = 388
	name = "{\"text\":\"Trinkets\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_brown"
	z = 48
	x = 329
	name = "{\"text\":\"Portable Tables\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = 62
	x = 309
	name = "{\"text\":\"WearThat\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_blue"
	z = -135
	x = 117
	name = "{\"text\":\"ElectricEel\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = -129
	x = 100
	name = "{\"text\":\"Map Shirts\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_black"
	z = -153
	x = 102
	name = "{\"text\":\"Polaroid Camera\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_gray"
	z = 124
	x = 209
	name = "{\"text\":\"Gravity API\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_yellow"
	z = -322
	x = -202
	name = "{\"text\":\"Endrous Edibles\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_light_blue"
	z = -75
	x = 73
	name = "{\"text\":\"Blåhaj\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_white"
	z = 217
	x = 15
	name = "{\"text\":\"Fabulously Optimized\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_gray"
	z = -439
	x = 113
	name = "{\"text\":\"ModernFix\"}"
	rotation = 180.0
	y = 0
	source = "user"

[[markers]]
	type = "banner_orange"
	z = -329
	x = -126
	name = "{\"text\":\"CHS\"}"
	rotation = 180.0
	y = 0
	source = "user"

